# Generated by Django 4.2.16 on 2024-10-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Taom turi')),
            ],
            options={
                'verbose_name': 'Taom turi',
                'verbose_name_plural': 'Taom turlari',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Taom nomi')),
                ('tarkibi', models.TextField(verbose_name='Tarkibi')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rilgan soni")),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.foodtype', verbose_name='Taom turi')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
            },
        ),
    ]
